version: "3.5"

x-common-environment: &common-environment
  image: node:14
  working_dir: /app
  volumes:
    - ./backend:/app
  restart: on-failure
  environment:
    REDIS_HOST: "redis"

    CHAIN_ID: "1"
    RPC_URL: "${RPC_URL}"

  depends_on:
    - redis

services:
  api:
    <<: *common-environment
    ports:
      - 3000:3000
    command: "npm run start"

  general_reserves_data_loader:
    <<: *common-environment
    command: "npm run job:update-general-reserves-data"

  reserves_incentives_data_loader:
    <<: *common-environment
    command: "npm run job:update-reserve-incentives-data"

  user_incentives_data_loader:
    <<: *common-environment
    command: "npm run job:update-users-incentives-data"

  user_data_loader:
    <<: *common-environment
    command: "npm run job:update-users-data"

  stake_user_ui_data_loader:
    <<: *common-environment
    command: "npm run job:update-stake-user-ui-data"

  stake_general_ui_data_loader:
    <<: *common-environment
    command: "npm run job:update-stake-general-ui-data"

  block_number_loader:
    <<: *common-environment
    command: "npm run job:update-block-number"

  redis:
    image: redis:6-alpine
