apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  labels: 
    {{- include "common.labels" . | nindent 4 }}
    component: redis
  annotations:
  {{- include "common.annotations" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
     component: redis
  template:
    metadata:
      annotations:
      {{- with .Values.redis.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- include "common.annotations" . | nindent 8 }}
      labels:
        {{- include "common.labels" . | nindent 8 }}
        component: redis
    spec:
      automountServiceAccountToken: false
      enableServiceLinks: false
      containers:
        - name: redis
          image: "{{ .Values.redis.image }}"
          imagePullPolicy: Always
          ports:
            - name: redis
              containerPort: 6379
              protocol: TCP
          resources:
            {{- toYaml .Values.redis.resources | nindent 12 }}
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    {{- include "common.labels" . | nindent 4 }}
    component: redis
  annotations:
  {{- include "common.annotations" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 6379
      targetPort: redis
      protocol: TCP
      name: redis
  selector:
    component: redis
