name: Stop preview env

on:
  pull_request:
    types: [closed]

jobs:
  stop_dev:
    runs-on: ubuntu-latest
    environment: preview
    container: 
      image: ghcr.io/helmfile/helmfile-ubuntu:v0.145.4
    strategy:
      fail-fast: false
      matrix:
        CHAIN_ID: ["1", "137", "43114"]
    steps:
      - name: Set k8s namespace
        shell: bash
        run: |
          cat <<EOF | tr -c '[:alnum:]-=\n' '-' >> ${GITHUB_ENV}
          NAMESPACE=cache-${NS_SUFFIX,,}
          EOF
        env:
          NS_SUFFIX: "${{ github.head_ref }}-${{ matrix.CHAIN_ID }}"

      - name: Remove preview env
        env:
          CHAIN_ID: '${{ matrix.CHAIN_ID }}'
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.DEV_KUBECONFIG }}" > ~/.kube/config
          kubectl -n "${NAMESPACE}" delete deploy --all
          sleep 5
          kubectl delete ns "${NAMESPACE}"
