name: Stop preview env

on:
  pull_request:
    types: [closed]

jobs:
  stop_dev:
    runs-on: ubuntu-latest
    environment: preview
    container: 
      image: registry.gitlab.com/aave-tech/k8s:63f618c0
      credentials:
        username: github-actions
        password: ${{ secrets.KUBE_IMAGE_PULL }}
    steps:

      - name: Set k8s namespace
        shell: bash
        run:
          echo "NAMESPACE=cache-${REF_NAME,,}" | tr -c '[:alnum:]-=\n' '-' >>${GITHUB_ENV}
        env:
          REF_NAME: '${{ github.head_ref }}'

      - name: Remove preview env
        env:
          REF_NAME: '${{ github.head_ref }}'
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.DEV_KUBECONFIG }}" > ~/.kube/config
          kubectl config set-context --current --namespace="${{ env.NAMESPACE }}"
          kubectl delete deploy --all
          kubectl delete svc --all
          kubectl delete ingress --all
          kubectl delete ns "${{ env.NAMESPACE }}"
